site_name: Paper Documentation
docs_dir: .
theme: readthedocs
pages:
- Home: 'index.md'
- Get Paper: 'building.md'
- Features: 'features.md'
- Configuration: 'config.md'
- Developers: 'developers.md'
